In [306]:
import numpy as np

In [4]:
import pandas as pd

In [189]:
df=pd.read_csv("train.csv")


In [201]:
df=pd.DataFrame(df)
df=df.loc[:,["age_in_days","Income","target"]]

In [203]:

df.dropna(inplace=True)

In [205]:
df

age_in_days  Income  target
0            12058  355060       1
1            21546  315150       1
2            17531   84140       0
3            15341  250510       1
4            31400  198680       1
...            ...     ...     ...
79848        23367  224550       1
79849        19356  279150       1
79850        23372  305020       1
79851        22641   39330       1
79852        15709  280140       0

[76855 rows x 3 columns]

In [207]:
X=df.iloc[:,:-1]

In [209]:
X

age_in_days  Income
0            12058  355060
1            21546  315150
2            17531   84140
3            15341  250510
4            31400  198680
...            ...     ...
79848        23367  224550
79849        19356  279150
79850        23372  305020
79851        22641   39330
79852        15709  280140

[76855 rows x 2 columns]

In [211]:
y=df.iloc[:,-1]

In [213]:
y

0        1
1        1
2        0
3        1
4        1
        ..
79848    1
79849    1
79850    1
79851    1
79852    0
Name: target, Length: 76855, dtype: int64

In [215]:
from sklearn.model_selection import train_test_split

In [217]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [219]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [221]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [223]:
from sklearn.linear_model import LogisticRegression

In [225]:
model=LogisticRegression()

In [227]:
model.fit(X_train,y_train)

LogisticRegression()

In [229]:
y_pred=model.predict(X_test)

In [231]:
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [233]:
from sklearn.metrics import accuracy_score

In [235]:
ac=accuracy_score(y_test,y_pred)

In [237]:
ac

0.9383254179949255

In [239]:
from sklearn.neighbors import KNeighborsClassifier

In [241]:
knn=KNeighborsClassifier(n_neighbors=10)


In [243]:
knn.fit(X_train,y_train)


KNeighborsClassifier(n_neighbors=10)

In [245]:
y_pred1=knn.predict(X_test)

In [246]:
y_pred1


array([1, 1, 1, ..., 1, 1, 1])

In [249]:
knnac=accuracy_score(y_test,y_pred1)

In [251]:
knnac

0.9378049573872878

In [253]:
from sklearn.svm import SVC


In [255]:
svc_diag=SVC(C=10,kernel='rbf',gamma=2)

In [256]:
svc_diag.fit(X_train,y_train)

SVC(C=10, gamma=2)

In [259]:
y_pred2=svc_diag.predict(X_test)

In [260]:
y_pred2

array([1, 1, 1, ..., 1, 1, 1])

In [263]:
svmac=accuracy_score(y_test,y_pred1)

In [265]:
svmac

0.9378049573872878

In [267]:
from sklearn.tree import DecisionTreeClassifier


In [269]:
dtree = DecisionTreeClassifier()


In [271]:
dtree = dtree.fit(X_train, y_train)

In [273]:
ypred3=dtree.predict(X_test)
ypred3



array([1, 1, 1, ..., 1, 1, 1])

In [275]:
dtac=accuracy_score(y_test,ypred3)

In [277]:
dtac

0.8796434844837682

In [279]:
from sklearn.ensemble import RandomForestClassifier

In [281]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [283]:
y_pred4= rf.predict(X_test)

In [285]:
rfac=accuracy_score(y_test,y_pred4)
rfac

0.9296727603929478

In [326]:
################  QUESTION 1 #######################


p1=model.predict([[10950,87000]])
p2=knn.predict([[10950,87000]])
p3=svc_diag.predict([[10950,87000]])  #age 40, salary 87000
p4=dtree.predict([[10950,87000]])
p5=rf.predict([[10950,87000]])
print("prediction of logistic regression",p1)
print("prediction of knn",p2)
print("prediction of decision tree",p3)
print("prediction of svm",p4)
print("prediction of random forest",p5)

prediction of logistic regression [1]
prediction of knn [1]
prediction of decision tree [1]
prediction of svm [1]
prediction of random forest [1]


In [330]:
q1=model.predict([[14600,0]])
q2=knn.predict([[14600,0]])
q3=svc_diag.predict([[14600,0]])                               #age 40,salary 0
q4=dtree.predict([[14600,0]])
q5=rf.predict([[14600,0]])
print("prediction of logistic regression",q1)
print("prediction of knn",q2)
print("prediction of decision tree",q3)
print("prediction of svm",q4)
print("prediction of random forest",q5)

prediction of logistic regression [1]
prediction of knn [1]
prediction of decision tree [1]
prediction of svm [1]
prediction of random forest [1]


In [332]:
r1=model.predict([[14600,100000]])
r2=knn.predict([[14600,100000]])
r3=svc_diag.predict([[14600,100000]])                       #age 40,salary 100000
r4=dtree.predict([[14600,100000]])
r5=rf.predict([[14600,10000]])
print("prediction of logistic regression",r1)
print("prediction of knn",r2)
print("prediction of decision tree",r3)
print("prediction of svm",r4)
print("prediction of random forest",r5)

prediction of logistic regression [1]
prediction of knn [1]
prediction of decision tree [1]
prediction of svm [1]
prediction of random forest [1]


In [334]:
s1=model.predict([[18250,0]])
s2=knn.predict([[18250,0]])
s3=svc_diag.predict([[18250,0]])                          #age 50,salary 0
s4=dtree.predict([[18250,0]])
s5=rf.predict([[18250,0]])
print("prediction of logistic regression",s1)
print("prediction of knn",s2)
print("prediction of decision tree",s3)
print("prediction of svm",s4)
print("prediction of random forest",s5)

prediction of logistic regression [1]
prediction of knn [1]
prediction of decision tree [1]
prediction of svm [1]
prediction of random forest [1]


In [336]:
#################### QUESTION 2 ##########################

In [338]:
P1=model.predict([[6570,0]])
P2=knn.predict([[6570,0]])
P3=svc_diag.predict([[6570,0]])                            #age 18, salary 0
P4=dtree.predict([[6570,0]])
P5=rf.predict([[6570,0]])
print("prediction of logistic regression",P1)
print("prediction of knn",P2)
print("prediction of decision tree",P3)
print("prediction of svm",p4)
print("prediction of random forest",P5)

prediction of logistic regression [1]
prediction of knn [1]
prediction of decision tree [1]
prediction of svm [1]
prediction of random forest [1]


In [340]:
R1=model.predict([[8030,600000]])
R2=knn.predict([[8030,600000]])
R3=svc_diag.predict([[8030,600000]])                            #age 22, salary 600000
R4=dtree.predict([[8030,600000]])
R5=rf.predict([[8030,600000]])
print("prediction of logistic regression",R1)
print("prediction of knn",R2)
print("prediction of decision tree",R3)
print("prediction of svm",R4)
print("prediction of random forest",R5)

prediction of logistic regression [1]
prediction of knn [1]
prediction of decision tree [1]
prediction of svm [1]
prediction of random forest [1]


In [344]:
S1=model.predict([[21900,100000000]])
S2=knn.predict([[21900,100000000]])
S3=svc_diag.predict([[21900,100000000]])                            #age 35, salary 2500000
S4=dtree.predict([[21900,100000000]])
S5=rf.predict([[21900,100000000]])
print("prediction of logistic regression",S1)
print("prediction of knn",S2)
print("prediction of decision tree",S3)
print("prediction of svm",S4)
print("prediction of random forest",S5)

prediction of logistic regression [1]
prediction of knn [1]
prediction of decision tree [1]
prediction of svm [1]
prediction of random forest [1]


In [346]:
Q1=model.predict([[12755,2500000]])
Q2=knn.predict([[12755,2500000]])
Q3=svc_diag.predict([[12755,2500000]])                            #age 60, salary 100000000
Q4=dtree.predict([[12755,2500000]])
Q5=rf.predict([[12755,2500000]])
print("prediction of logistic regression",Q1)
print("prediction of knn",Q2)
print("prediction of decision tree",Q3)
print("prediction of svm",Q4)
print("prediction of random forest",Q5)

prediction of logistic regression [1]
prediction of knn [1]
prediction of decision tree [1]
prediction of svm [1]
prediction of random forest [1]
